# repos:
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.2.1
#     hooks:
#     -   id: ruff
#         args: [--fix, --exit-non-zero-on-fix]
#     -   id: ruff-format
#         args: [--line-length=120]
# -   repo: local
#     hooks:
#     -   id: pytest-check
#         name: pytest-check
#         entry: bash -c 'if [ -d "tests" ] && [ "$(find tests -name "test_*.py" | wc -l)" -gt 0 ]; then pytest tests/ --cov=src --cov-report=term-missing --exitfirst; else echo "No tests found - skipping pytest"; exit 0; fi'
#         language: system
#         pass_filenames: false
#         always_run: true


repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
        args: [--line-length=120]
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
            "tests/",
            "--cov=src",
            "--cov-report=term-missing",
            "--exitfirst"
        ]
