[project]
name = "pytest-insight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jeffrey Wright", email = "jeffrey.wright@wartsila.com" }
]
requires-python = ">=3.9.16"
dependencies = [
    "hatch>=1.14.0",
    "pre-commit>=4.1.0",
    "pytest>=6.2",
    "pytest-rerunfailures>=15.0",
    "isort>=6.0.0",
    "pyflakes>=3.2.0",
    "black>=25.1.0",
]

[project.entry-points.pytest11]
insight = "pytest_insight.plugin"

[project.scripts]
pytest-insight = "pytest_insight:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"
line_length = 120


[tool.ruff]
line-length = 120
fix = true
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.9.6",
]
