[theme]
# Primary accent color for interactive elements
primaryColor = "#7792E3"

# Background color for the main content area
backgroundColor = "#1E1E1E"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#252526"

# Color used for almost all text
textColor = "#FAFAFA"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

# Dark mode
base = "dark"
